version: '3'
services:
  mtauthserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: mtauthserver
    container_name: mtauthserver
    ports:
      - "8080:8080"
    env_file:
      - .env
